<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-29T16:24:02+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'fr_FR',
    'version_installed' => '8.3.1',
    'version_db_installed' => '20171218000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1521034524,
        'latest_version' => '8.3.1',
        'do_page_reindex_check' => false,
    ],
];
