<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-14T14:29:02+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'admin',
        ],
    ],
];
